name: Build, publish and deploy project to Simply

on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.200
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with .NET
        run: dotnet test --configuration Release --no-build

      - name: Publish
        run: dotnet publish --configuration Release --no-build -o publish

      - name: Deploy to Simply        
        uses: talunzhang/auto-web-deploy@v1.0.1
        with:
          website-name: soulthief-001-site1
          server-computer-name: https://win9079.site4now.net:8172
          server-username: soulthief-001
          server-password: Sofia270307@
          source-path: 'publish'